name: Release Go project

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:

jobs:
  builds:
    - main: ./cmd/slowql-digest/
      id: "digest"
      binary: digest_{{ .Version }}_{{ .OS }}_{{ .Arch }}
      goos:
        - linux
        - darwin
        - windows
  
    - main: ./cmd/slowql-replayer/
      id: "replayer"
      binary: replayer_{{ .Version }}_{{ .OS }}_{{ .Arch }}
      goos:
        - linux
        - darwin
        - windows

    name: GoReleaser build
    runs-on: ubuntu-latest

  steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
      id: go
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}